version: "3"

services: 
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: databasetest
    image: mongo
    ports: 
      - "27017:27017"